explorer:
  host: 127.0.0.1
  port: 8080
  secret: "CHOOSE A SECRET DAMMIT"

nuls:
  base_uri: "http://beta.wallet.nuls.io/api/"
  chain_id: 2

mongodb:
  uri: "mongodb://127.0.0.1:27017"
  database: nuls2test

aleph_client:
  enabled: True
  private_key: null
  api_server: https://api1.aleph.im